universe                = vanilla
executable              = /home/glbrc.org/narhmadey/2.Y1000_267_phylogenetics/2_Plant_Path_563/scripts/run_beast_job.sh
arguments               = "$(og_name)"
log                     = /home/glbrc.org/narhmadey/2.Y1000_267_phylogenetics/2_Plant_Path_563/logs/beast_$(ClusterId).$(ProcId).log
output                  = /home/glbrc.org/narhmadey/2.Y1000_267_phylogenetics/2_Plant_Path_563/logs/beast_$(ClusterId).$(ProcId).out
error                   = /home/glbrc.org/narhmadey/2.Y1000_267_phylogenetics/2_Plant_Path_563/logs/beast_$(ClusterId).$(ProcId).error
request_cpus            = 4
request_memory          = 16GB
request_disk            = 10GB
environment             = "OMP_NUM_THREADS=4"
notify_user             = narhmadey@wisc.edu
notification            = Always
max_retries             = 1
on_exit_remove          = (ExitBySignal == False) && (ExitCode == 0)
queue og_name from /home/glbrc.org/narhmadey/2.Y1000_267_phylogenetics/2_Plant_Path_563/scripts/beast_jobs.txt
